# 敏感词配置文件
# 此文件包含需要过滤的敏感词列表
# 所有列表中的词在评论中将被替换为"**"

sensitive_words:
  - 傻逼
  - 操你妈
  - 混蛋
  - stupid
  - idiot
  - 法轮功
  - 共产党
  - 政治局
  - porn
  - 色情
  - 赌博
  - 欺诈
  - 诈骗
  - 王八蛋
  - 白痴
  - 垃圾
  - fuck
  - bitch
  - asshole
  - 博彩
  - 毒品
  - 黄赌毒
  - 网络诈骗