# sensitive words list
words:
  - 傻逼
  - 白痴
  - sb
  - 智障
  - fuck
  - shit
  - bitch
  - porn
  - 色情
  - 赌博
  - 博彩
  - 操你妈
  - 草泥马
  - 傻缺
  - 垃圾
  - 废物
  - 死
  - 滚蛋
  - 混蛋
  - 笨蛋
  - 王八蛋
  - 龟儿子
  - 废话
  - 放屁
  - 妈蛋
  - tmd
  - 他妈的
  - 狗屁
  - 扯淡
  - 牛逼
  - 吹牛
  - 装逼
  - 装B
  - 装比
  - 日你
  - ri你
  - 我日
  - wo日
  - 我cao
  - 我艹
  - 我操
  - 卧槽
  - wocao
  - 脑残
  - 你妹
  - nmb
  - 尼玛
  - nm
  - 你妈
  - 你爸
  - 你大爷
  - 滚
  - 去死